// Machine generated code

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.10.1
// source: box_example.service.proto

package pbdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_example_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_box_example_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_box_example_service_proto_rawDescGZIP(), []int{0}
}

type TestCaller_SetInfoArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arg1 string `protobuf:"bytes,1,opt,name=arg1,proto3" json:"arg1,omitempty"`
}

func (x *TestCaller_SetInfoArgs) Reset() {
	*x = TestCaller_SetInfoArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_example_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCaller_SetInfoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaller_SetInfoArgs) ProtoMessage() {}

func (x *TestCaller_SetInfoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_box_example_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaller_SetInfoArgs.ProtoReflect.Descriptor instead.
func (*TestCaller_SetInfoArgs) Descriptor() ([]byte, []int) {
	return file_box_example_service_proto_rawDescGZIP(), []int{1}
}

func (x *TestCaller_SetInfoArgs) GetArg1() string {
	if x != nil {
		return x.Arg1
	}
	return ""
}

type TestCaller_GetInfoArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestCaller_GetInfoArgs) Reset() {
	*x = TestCaller_GetInfoArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_example_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCaller_GetInfoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaller_GetInfoArgs) ProtoMessage() {}

func (x *TestCaller_GetInfoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_box_example_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaller_GetInfoArgs.ProtoReflect.Descriptor instead.
func (*TestCaller_GetInfoArgs) Descriptor() ([]byte, []int) {
	return file_box_example_service_proto_rawDescGZIP(), []int{2}
}

type TestCallee_AddArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arg1 int32 `protobuf:"varint,1,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2 int32 `protobuf:"varint,2,opt,name=arg2,proto3" json:"arg2,omitempty"`
}

func (x *TestCallee_AddArgs) Reset() {
	*x = TestCallee_AddArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_example_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCallee_AddArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCallee_AddArgs) ProtoMessage() {}

func (x *TestCallee_AddArgs) ProtoReflect() protoreflect.Message {
	mi := &file_box_example_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCallee_AddArgs.ProtoReflect.Descriptor instead.
func (*TestCallee_AddArgs) Descriptor() ([]byte, []int) {
	return file_box_example_service_proto_rawDescGZIP(), []int{3}
}

func (x *TestCallee_AddArgs) GetArg1() int32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *TestCallee_AddArgs) GetArg2() int32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

type TestCallee_SubArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arg1 int32 `protobuf:"varint,1,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2 int32 `protobuf:"varint,2,opt,name=arg2,proto3" json:"arg2,omitempty"`
}

func (x *TestCallee_SubArgs) Reset() {
	*x = TestCallee_SubArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_example_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCallee_SubArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCallee_SubArgs) ProtoMessage() {}

func (x *TestCallee_SubArgs) ProtoReflect() protoreflect.Message {
	mi := &file_box_example_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCallee_SubArgs.ProtoReflect.Descriptor instead.
func (*TestCallee_SubArgs) Descriptor() ([]byte, []int) {
	return file_box_example_service_proto_rawDescGZIP(), []int{4}
}

func (x *TestCallee_SubArgs) GetArg1() int32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *TestCallee_SubArgs) GetArg2() int32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

type TestCaller_SetInfoRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestCaller_SetInfoRet) Reset() {
	*x = TestCaller_SetInfoRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_example_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCaller_SetInfoRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaller_SetInfoRet) ProtoMessage() {}

func (x *TestCaller_SetInfoRet) ProtoReflect() protoreflect.Message {
	mi := &file_box_example_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaller_SetInfoRet.ProtoReflect.Descriptor instead.
func (*TestCaller_SetInfoRet) Descriptor() ([]byte, []int) {
	return file_box_example_service_proto_rawDescGZIP(), []int{5}
}

type TestCaller_GetInfoRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret1 string `protobuf:"bytes,1,opt,name=ret1,proto3" json:"ret1,omitempty"`
}

func (x *TestCaller_GetInfoRet) Reset() {
	*x = TestCaller_GetInfoRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_example_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCaller_GetInfoRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaller_GetInfoRet) ProtoMessage() {}

func (x *TestCaller_GetInfoRet) ProtoReflect() protoreflect.Message {
	mi := &file_box_example_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaller_GetInfoRet.ProtoReflect.Descriptor instead.
func (*TestCaller_GetInfoRet) Descriptor() ([]byte, []int) {
	return file_box_example_service_proto_rawDescGZIP(), []int{6}
}

func (x *TestCaller_GetInfoRet) GetRet1() string {
	if x != nil {
		return x.Ret1
	}
	return ""
}

type TestCallee_AddRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret1 int32 `protobuf:"varint,1,opt,name=ret1,proto3" json:"ret1,omitempty"`
}

func (x *TestCallee_AddRet) Reset() {
	*x = TestCallee_AddRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_example_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCallee_AddRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCallee_AddRet) ProtoMessage() {}

func (x *TestCallee_AddRet) ProtoReflect() protoreflect.Message {
	mi := &file_box_example_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCallee_AddRet.ProtoReflect.Descriptor instead.
func (*TestCallee_AddRet) Descriptor() ([]byte, []int) {
	return file_box_example_service_proto_rawDescGZIP(), []int{7}
}

func (x *TestCallee_AddRet) GetRet1() int32 {
	if x != nil {
		return x.Ret1
	}
	return 0
}

type TestCallee_SubRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret1 int32 `protobuf:"varint,1,opt,name=ret1,proto3" json:"ret1,omitempty"`
}

func (x *TestCallee_SubRet) Reset() {
	*x = TestCallee_SubRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_example_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCallee_SubRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCallee_SubRet) ProtoMessage() {}

func (x *TestCallee_SubRet) ProtoReflect() protoreflect.Message {
	mi := &file_box_example_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCallee_SubRet.ProtoReflect.Descriptor instead.
func (*TestCallee_SubRet) Descriptor() ([]byte, []int) {
	return file_box_example_service_proto_rawDescGZIP(), []int{8}
}

func (x *TestCallee_SubRet) GetRet1() int32 {
	if x != nil {
		return x.Ret1
	}
	return 0
}

var File_box_example_service_proto protoreflect.FileDescriptor

var file_box_example_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x62, 0x6f, 0x78, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x6f, 0x78,
	0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x2d, 0x0a, 0x17, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x5f,
	0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x31,
	0x22, 0x19, 0x0a, 0x17, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x22, 0x3d, 0x0a, 0x13, 0x54,
	0x65, 0x73, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x5f, 0x41, 0x64, 0x64, 0x5f, 0x61, 0x72,
	0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x61, 0x72, 0x67, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x32, 0x22, 0x3d, 0x0a, 0x13, 0x54, 0x65,
	0x73, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x5f, 0x53, 0x75, 0x62, 0x5f, 0x61, 0x72, 0x67,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x32, 0x22, 0x18, 0x0a, 0x16, 0x54, 0x65, 0x73,
	0x74, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x5f,
	0x72, 0x65, 0x74, 0x22, 0x2c, 0x0a, 0x16, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x65, 0x74, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x74,
	0x31, 0x22, 0x28, 0x0a, 0x12, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x5f,
	0x41, 0x64, 0x64, 0x5f, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x74, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x65, 0x74, 0x31, 0x22, 0x28, 0x0a, 0x12, 0x54,
	0x65, 0x73, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x5f, 0x53, 0x75, 0x62, 0x5f, 0x72, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x74, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x72, 0x65, 0x74, 0x31, 0x42, 0x10, 0x5a, 0x0e, 0x69, 0x64, 0x6c, 0x64, 0x61, 0x74, 0x61,
	0x2f, 0x70, 0x62, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_box_example_service_proto_rawDescOnce sync.Once
	file_box_example_service_proto_rawDescData = file_box_example_service_proto_rawDesc
)

func file_box_example_service_proto_rawDescGZIP() []byte {
	file_box_example_service_proto_rawDescOnce.Do(func() {
		file_box_example_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_box_example_service_proto_rawDescData)
	})
	return file_box_example_service_proto_rawDescData
}

var file_box_example_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_box_example_service_proto_goTypes = []interface{}{
	(*Empty)(nil),                  // 0: box_example.Empty
	(*TestCaller_SetInfoArgs)(nil), // 1: box_example.TestCaller_SetInfo_args
	(*TestCaller_GetInfoArgs)(nil), // 2: box_example.TestCaller_GetInfo_args
	(*TestCallee_AddArgs)(nil),     // 3: box_example.TestCallee_Add_args
	(*TestCallee_SubArgs)(nil),     // 4: box_example.TestCallee_Sub_args
	(*TestCaller_SetInfoRet)(nil),  // 5: box_example.TestCaller_SetInfo_ret
	(*TestCaller_GetInfoRet)(nil),  // 6: box_example.TestCaller_GetInfo_ret
	(*TestCallee_AddRet)(nil),      // 7: box_example.TestCallee_Add_ret
	(*TestCallee_SubRet)(nil),      // 8: box_example.TestCallee_Sub_ret
}
var file_box_example_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_box_example_service_proto_init() }
func file_box_example_service_proto_init() {
	if File_box_example_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_box_example_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_example_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCaller_SetInfoArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_example_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCaller_GetInfoArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_example_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCallee_AddArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_example_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCallee_SubArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_example_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCaller_SetInfoRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_example_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCaller_GetInfoRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_example_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCallee_AddRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_example_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCallee_SubRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_box_example_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_box_example_service_proto_goTypes,
		DependencyIndexes: file_box_example_service_proto_depIdxs,
		MessageInfos:      file_box_example_service_proto_msgTypes,
	}.Build()
	File_box_example_service_proto = out.File
	file_box_example_service_proto_rawDesc = nil
	file_box_example_service_proto_goTypes = nil
	file_box_example_service_proto_depIdxs = nil
}
