package idlrpc

import "context"

//IService user custom service framework interface
type IService interface {

	// GetUUID service uuid, generated by rpc-repo
	GetUUID() uint64

	// GetNickName return custom service nickname !
	GetNickName() string

	// OnAfterFork init service by framework, user can init some custom data in this function
	OnAfterFork(ctx context.Context) bool

	// OnTick tick your service the same goroutine
	OnTick() bool

	// OnBeforeDestroy before service unload, you can clean your own data in this func
	OnBeforeDestroy() bool
}

//ServiceCreator service creator
type ServiceCreator func(interface{}) IService
